resources:
  - ../../base
  - postgres-local.yml 
  - local-ingress.yml
  - kafka-local.yml
  - kafka-ui-local.yml
  - mongodb-local.yml
patches:
  - path: ms-products-configmap-patch.yml
  - path: ms-products-secret-patch.yml
  - path: log-ingestor-configmap-patch.yml
  - path: log-ingestor-secret-patch.yml
  - path: ms-auth-configmap-patch.yml
  - path: ms-auth-secret-patch.yml
  - path: api-gateway-secret-patch.yml
  - path: ms-cms-configmap-patch.yml
  - path: ms-cms-secret-patch.yml