resources:
  - ../../base
  - postgres-local.yml 
  - local-ingress.yml
  - kafka-local.yml
  - kafka-ui-local.yml
patches:
  - path: product-backend-configmap-patch.yml
  - path: product-backend-secret-patch.yml
  - path: log-ingestor-configmap-patch.yml
  - path: log-ingestor-secret-patch.yml
  - path: ms-auth-configmap-patch.yml
  - path: ms-auth-secret-patch.yml