apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    # ---------------------------------------------
    # 1. Ton application principale (Front + Back)
    # ---------------------------------------------
    - host: product-app.local
      http:
        paths:
          - path: /api/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: product-backend-service
                port:
                  number: 8080
          - path: /?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: product-frontend-service
                port:
                  number: 80

    # ---------------------------------------------
    # 2. La nouvelle interface Kafka UI
    # ---------------------------------------------
    - host: kafka.product-app.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kafka-ui-service
                port:
                  number: 80