apiVersion: v1
kind: Secret
metadata:
  name: ms-auth-secrets
type: Opaque
data:
  # On met une valeur qui n'a pas de tirets (ex: "cle_secrete_sans_tirets")
  # echo -n "cle_secrete_sans_tirets" | base64 -> Y2xlX3NlY3JldGVfc2FfbmVfdGlyZXRz
  JWT_SECRET: OHc5ZUs3c1ZoM0ZRMm1KNmxQMHJYeVp0TjFiUTR1RGtGdkhzVDJjVytFbz0=
  DB_USER: dXNlcg==
  DB_PASSWORD: cGFzc3dvcmQ=

