apiVersion: v1
kind: Secret
metadata:
  name: ms-cms-secrets
type: Opaque
data:
  # Valeurs encodées en base64 (ex: echo -n 'admin' | base64)
  MONGO_USER: YWRtaW4= 
  MONGO_PASSWORD: cGFzc3dvcmQ=
  JWT_SECRET: OHc5ZUs3c1ZoM0ZRMm1KNmxQMHJYeVp0TjFiUTR1RGtGdkhzVDJjVytFbz0=