apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-jobs-config
data:
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "ms_jobs"
  JWT_EXPIRED_TIME: "86400" # 24 heures
  LOGS_SERVER_HOST: "log-ingestor-service:50051"
