apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
data:
  init-auth-db.sh: |
    #!/bin/bash
    set -e
    # Ce script est exécuté automatiquement par l'image Postgres au premier démarrage
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
        CREATE DATABASE "ms_auth";
    EOSQL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "product_db" # La base principale
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: product-backend-secrets
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: product-backend-secrets
                  key: DB_PASSWORD
          # On monte le ConfigMap comme un dossier dans le conteneur
          volumeMounts:
            - name: init-script-volume
              mountPath: /docker-entrypoint-initdb.d/
      volumes:
        - name: init-script-volume
          configMap:
            name: postgres-init-script
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432