apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            # On utilise les mêmes secrets que le backend pour la cohérence
            - name: POSTGRES_DB
              value: "product_db"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: product-backend-secrets
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: product-backend-secrets
                  key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service  # C'est ce nom que ton Backend utilise dans DB_HOST
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432