resources:
  - ../../base
patches:
  - path: product-backend-config-patch.yml
  - path: product-backend-secret-patch.yml
  - path: log-ingestor-config-patch.yml
  - path: log-ingestor-secret-patch.yml
  - path: ms-auth-config-patch.yml
  - path: ms-auth-secret-patch.yml
  - path: api-gateway-secret-patch.yml