resources:
  - ../../base
patches:
  - path: product-backend-config-patch.yml
  - path: product-backend-secret-patch.yml
  - path: log-ingestor-config-patch.yml
  - path: log-ingestor-secret-patch.yml