resources:
  - ../../base
patches:
  - path: ms-products-config-patch.yml
  - path: ms-products-secret-patch.yml
  - path: log-ingestor-config-patch.yml
  - path: log-ingestor-secret-patch.yml
  - path: ms-auth-config-patch.yml
  - path: ms-auth-secret-patch.yml
  - path: api-gateway-secret-patch.yml
  - path: ms-cms-config-patch.yml
  - path: ms-cms-secret-patch.yml