apiVersion: v1
kind: Secret
metadata:
  name: log-ingestor-secrets
type: Opaque
stringData: # Utilise stringData pour écrire en clair (K8s l'encodera en base64 pour toi)
  KAFKA_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required username='${KAFKA_USER_PROD}' password='${KAFKA_PASS_PROD}';"