apiVersion: v1
kind: Secret
metadata:
  name: ms-cms-secrets
type: Opaque
data:
  # Valeurs encodées en base64 (ex: echo -n 'admin' | base64)
  MONGO_USER: ${MONGO_USER_PROD}
  MONGO_PASSWORD: ${MONGO_PASSWORD_PROD}
  JWT_SECRET: ${JWT_SECRET_PROD}