apiVersion: v1
kind: Secret
metadata:
  name: product-backend-secrets
type: Opaque
data:
  # Ces valeurs seront injectées par GitHub Actions
  DB_USER: "${DB_USER_PROD}"
  DB_PASSWORD: "${DB_PASSWORD_PROD}"
  JWT_SECRET: "${JWT_SECRET_PROD}"