apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      component: api-gateway
  template:
    metadata:
      labels:
        component: api-gateway
    spec: 
      containers:
        - name: api-gateway
          image: magnomos/api-gateway
          ports: 
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: api-gateway-secrets