apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-front-angular-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      component: app-front-angular
  template:
    metadata:
      labels:
        component: app-front-angular
    spec: 
      containers:
        - name: app-front-angular
          image: magnomos/app-front-angular
          ports: 
            - containerPort: 80
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-front-angular-config
                  key: APP_PROFILE