apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ms-products-deployment.yml
  - ms-products-service.yml
  - ms-products-configmap.yml
  - ms-products-secret.yml
  - app-front-angular-deployment.yml
  - app-front-angular-service.yml
  - app-front-angular-configmap.yml
  - log-ingestor-deployment.yml
  - log-ingestor-service.yml
  - log-ingestor-configmap.yml
  - log-ingestor-secret.yml
  - ms-auth-deployment.yml
  - ms-auth-service.yml
  - ms-auth-configmap.yml
  - ms-auth-secret.yml
  - api-gateway-deployment.yml
  - api-gateway-service.yml
  - api-gateway-secret.yml
  - ms-cms-deployment.yml
  - ms-cms-service.yml
  - ms-cms-configmap.yml
  - ms-cms-secret.yml
  - ms-jobs-deployment.yml
  - ms-jobs-service.yml
  - ms-jobs-configmap.yml
  - ms-jobs-secret.yml