apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-products-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      component: ms-products
  template:
    metadata:
      labels:
        component: ms-products
    spec: 
      containers:
        - name: ms-products
          image: magnomos/ms.products
          ports: 
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: ms-products-config
            - secretRef:
                name: ms-products-secrets