apiVersion: v1
kind: Secret
metadata:
  name: product-backend-secrets
type: Opaque
data:
  # Valeurs encodées en base64 (ex: echo -n 'admin' | base64)
  DB_USER: YWRtaW4= 
  DB_PASSWORD: YWRtaW4=
  JWT_SECRET: bW9jay1zZWNyZXQ=